{
  parserClass="com.zhangfb95.plugins.mdp.parser.MdpParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Mdp"
  psiImplClassSuffix="Impl"
  psiPackage="com.zhangfb95.plugins.mdp.psi"
  psiImplPackage="com.zhangfb95.plugins.mdp.psi.impl"

  elementTypeHolderClass="com.zhangfb95.plugins.mdp.psi.MdpTypes"
  elementTypeClass="com.zhangfb95.plugins.mdp.psi.MdpElementType"
  tokenTypeClass="com.zhangfb95.plugins.mdp.psi.MdpTokenType"

  psiImplUtilClass="com.zhangfb95.plugins.mdp.psi.impl.MdpPsiImplUtil"

  tokens=[
    ANY=".*"
    COMMENT="<!--\".*\"-->"
    SPACE="\s*"

    WIKI_LINK_TEXT_START="["
    WIKI_LINK_TEXT_END="]"
    WIKI_LINK_REF_START="("
    WIKI_LINK_REF_END=")"
    WIKI_LINK_TEXT="regexp:[^[\[\]\(\)]]*"
    WIKI_LINK_REF="regexp:[^[\[\]\(\)]]*"
  ]
}

mdpFile ::= item_*

private item_ ::= (element|CRLF)

element ::= !<<eof>> (line)

line ::= (ANY? link ANY?)

link ::= (link_text SPACE? link_ref)

link_text ::= (WIKI_LINK_TEXT_START WIKI_LINK_TEXT WIKI_LINK_TEXT_END)
link_ref ::= (WIKI_LINK_REF_START wiki_link_ref_para WIKI_LINK_REF_END)

wiki_link_ref_para ::= WIKI_LINK_REF {
    mixin="com.zhangfb95.plugins.mdp.psi.impl.MdpNamedElementImpl"
    implements="com.zhangfb95.plugins.mdp.psi.MdpNamedElement"
    methods=[getNameIdentifier setName getName getReference]
}